modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MennoMax/astikor-carts/"
[[mods]]
modId="astikorcarts"
version="${file.jarVersion}"
displayName="AstikorCarts"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png"
authors="MennoMax"
description='''
This mod adds carts that can be pulled by other entities to the game.
To attach an entity, press the "Action Key" specified in the controls.

You might have to add the entity in the config file first.
'''

[[dependencies.astikorcarts]]
	modId = "forge"
	mandatory=true
	versionRange="[28.1.0,)"
	ordering="NONE"
	side="BOTH"
